window.MURAL_FOTOS = {
    "gerado":  "2026-08-06 18:16:51",
    "total":  343,
    "marcas":  {
                   "ALINARE":  [
                                   "_otimizadas/ALINARE/FESTA 3107/Estilizadas/anelprata.jpg",
                                   "_otimizadas/ALINARE/FESTA 3107/Estilizadas/brinco-colomb.jpg",
                                   "_otimizadas/ALINARE/FESTA 3107/Estilizadas/brincos colombiano.jpg",
                                   "_otimizadas/ALINARE/FESTA 3107/Estilizadas/brincosesmeralda.jpg",
                                   "_otimizadas/ALINARE/FESTA 3107/Estilizadas/colarrubi.jpg",
                                   "_otimizadas/ALINARE/FESTA 3107/FEST2102.jpg",
                                   "_otimizadas/ALINARE/FESTA 3107/FEST2110.jpg",
                                   "_otimizadas/ALINARE/FESTA 3107/FEST2116.jpg",
                                   "_otimizadas/ALINARE/FESTA 3107/FEST2119.jpg",
                                   "_otimizadas/ALINARE/FESTA 3107/FEST2120.jpg",
                                   "_otimizadas/ALINARE/FESTA 3107/FEST2133.jpg",
                                   "_otimizadas/ALINARE/FESTA 3107/FEST2134.jpg",
                                   "_otimizadas/ALINARE/FESTA 3107/FEST2141.jpg",
                                   "_otimizadas/ALINARE/FESTA 3107/FEST2144.jpg",
                                   "_otimizadas/ALINARE/FESTA 3107/FEST2149.jpg",
                                   "_otimizadas/ALINARE/FESTA 3107/FEST2173.jpg",
                                   "_otimizadas/ALINARE/FESTA 3107/FEST2178.jpg",
                                   "_otimizadas/ALINARE/FESTA 3107/FEST2184.jpg",
                                   "_otimizadas/ALINARE/FESTA 3107/FEST2193.jpg",
                                   "_otimizadas/ALINARE/FESTA 3107/FEST2201.jpg",
                                   "_otimizadas/ALINARE/FESTA 3107/FEST2205.jpg",
                                   "_otimizadas/ALINARE/FESTA 3107/FEST2209.jpg",
                                   "_otimizadas/ALINARE/FESTA 3107/FEST2232.jpg",
                                   "_otimizadas/ALINARE/FESTA 3107/FEST2236.jpg",
                                   "_otimizadas/ALINARE/FESTA 3107/FEST2240.jpg",
                                   "_otimizadas/ALINARE/FESTA 3107/FEST2244.jpg",
                                   "_otimizadas/ALINARE/FESTA 3107/FEST2256.jpg",
                                   "_otimizadas/ALINARE/FESTA 3107/FEST2259.jpg",
                                   "_otimizadas/ALINARE/FESTA 3107/FEST2268.jpg",
                                   "_otimizadas/ALINARE/FESTA 3107/FEST2275.jpg",
                                   "_otimizadas/ALINARE/FESTA 3107/FEST2277.jpg",
                                   "_otimizadas/ALINARE/GREGO_SEM DATA/5L5A0088-Editar.jpg",
                                   "_otimizadas/ALINARE/GREGO_SEM DATA/5L5A0090-Editar.jpg",
                                   "_otimizadas/ALINARE/GREGO_SEM DATA/5L5A0094-Editar.jpg",
                                   "_otimizadas/ALINARE/GREGO_SEM DATA/GREGO1768.jpg",
                                   "_otimizadas/ALINARE/GREGO_SEM DATA/GREGO1769.jpg",
                                   "_otimizadas/ALINARE/GREGO_SEM DATA/GREGO1771.jpg",
                                   "_otimizadas/ALINARE/GREGO_SEM DATA/GREGO1772.jpg",
                                   "_otimizadas/ALINARE/GREGO_SEM DATA/GREGO1783.jpg",
                                   "_otimizadas/ALINARE/GREGO_SEM DATA/GREGO1786.jpg",
                                   "_otimizadas/ALINARE/GREGO_SEM DATA/GREGO1791 copia.jpg",
                                   "_otimizadas/ALINARE/GREGO_SEM DATA/GREGO1791.jpg",
                                   "_otimizadas/ALINARE/GREGO_SEM DATA/GREGO1796.jpg",
                                   "_otimizadas/ALINARE/GREGO_SEM DATA/GREGO1806.jpg",
                                   "_otimizadas/ALINARE/GREGO_SEM DATA/GREGO1810.jpg",
                                   "_otimizadas/ALINARE/GREGO_SEM DATA/GREGO1813.jpg",
                                   "_otimizadas/ALINARE/GREGO_SEM DATA/GREGO1817.jpg",
                                   "_otimizadas/ALINARE/GREGO_SEM DATA/GREGO1828.jpg",
                                   "_otimizadas/ALINARE/GREGO_SEM DATA/GREGO1831.jpg",
                                   "_otimizadas/ALINARE/GREGO_SEM DATA/GREGO1833.jpg",
                                   "_otimizadas/ALINARE/GREGO_SEM DATA/GREGO1835.jpg",
                                   "_otimizadas/ALINARE/GREGO_SEM DATA/GREGO1846.jpg",
                                   "_otimizadas/ALINARE/GREGO_SEM DATA/GREGO1852.jpg",
                                   "_otimizadas/ALINARE/GREGO_SEM DATA/GREGO1881.jpg",
                                   "_otimizadas/ALINARE/GREGO_SEM DATA/GREGO1891.jpg",
                                   "_otimizadas/ALINARE/GREGO_SEM DATA/GREGO1966.jpg",
                                   "_otimizadas/ALINARE/GREGO_SEM DATA/GREGO1968.jpg",
                                   "_otimizadas/ALINARE/GREGO_SEM DATA/GREGO1979.jpg",
                                   "_otimizadas/ALINARE/GREGO_SEM DATA/GREGO1996.jpg",
                                   "_otimizadas/ALINARE/GREGO_SEM DATA/GREGO1999.jpg",
                                   "_otimizadas/ALINARE/GREGO_SEM DATA/GREGO2025.jpg",
                                   "_otimizadas/ALINARE/GREGO_SEM DATA/GREGO2046.jpg",
                                   "_otimizadas/ALINARE/GREGO_SEM DATA/GREGO2060.jpg",
                                   "_otimizadas/ALINARE/GREGO_SEM DATA/GREGO2075.jpg",
                                   "_otimizadas/ALINARE/LUMINOUS POCKET 1_30\u0026#x3a;07 3107/PCKT01.jpg",
                                   "_otimizadas/ALINARE/LUMINOUS POCKET 1_30\u0026#x3a;07 3107/PCKT02.jpg",
                                   "_otimizadas/ALINARE/LUMINOUS POCKET 1_30\u0026#x3a;07 3107/PCKT03.jpg",
                                   "_otimizadas/ALINARE/LUMINOUS POCKET 1_30\u0026#x3a;07 3107/PCKT04.jpg",
                                   "_otimizadas/ALINARE/LUMINOUS POCKET 1_30\u0026#x3a;07 3107/POCKET1AGO6506.jpg",
                                   "_otimizadas/ALINARE/LUMINOUS POCKET 1_30\u0026#x3a;07 3107/POCKET1AGO6507.jpg",
                                   "_otimizadas/ALINARE/LUMINOUS POCKET 1_30\u0026#x3a;07 3107/POCKET1AGO6519.jpg",
                                   "_otimizadas/ALINARE/LUMINOUS POCKET 1_30\u0026#x3a;07 3107/POCKET1AGO6531.jpg",
                                   "_otimizadas/ALINARE/LUMINOUS POCKET 1_30\u0026#x3a;07 3107/POCKET1AGO6555.jpg",
                                   "_otimizadas/ALINARE/LUMINOUS POCKET 1_30\u0026#x3a;07 3107/POCKET1AGO6564.jpg",
                                   "_otimizadas/ALINARE/LUMINOUS POCKET 1_30\u0026#x3a;07 3107/POCKET1AGO6570.jpg",
                                   "_otimizadas/ALINARE/LUMINOUS POCKET 1_30\u0026#x3a;07 3107/POCKET1AGO6613.jpg",
                                   "_otimizadas/ALINARE/LUMINOUS POCKET 1_30\u0026#x3a;07 3107/POCKET1AGO6639.jpg",
                                   "_otimizadas/ALINARE/LUMINOUS POCKET 1_30\u0026#x3a;07 3107/POCKET1AGO6648.jpg",
                                   "_otimizadas/ALINARE/LUMINOUS POCKET 1_30\u0026#x3a;07 3107/POCKET1AGO6666.jpg",
                                   "_otimizadas/ALINARE/LUMINOUS POCKET 1_30\u0026#x3a;07 3107/POCKET1AGO6691.jpg",
                                   "_otimizadas/ALINARE/LUMINOUS POCKET 1_30\u0026#x3a;07 3107/POCKET1AGO6695.jpg",
                                   "_otimizadas/ALINARE/LUMINOUS POCKET 1_30\u0026#x3a;07 3107/POCKET1AGO6700.jpg",
                                   "_otimizadas/ALINARE/LUMINOUS POCKET 1_30\u0026#x3a;07 3107/POCKET1AGO6712.jpg",
                                   "_otimizadas/ALINARE/LUMINOUS POCKET 1_30\u0026#x3a;07 3107/POCKET1AGO6724.jpg",
                                   "_otimizadas/ALINARE/LUMINOUS POCKET 1_30\u0026#x3a;07 3107/POCKET1AGO6741.jpg",
                                   "_otimizadas/ALINARE/LUMINOUS POCKET 1_30\u0026#x3a;07 3107/POCKET1AGO6768.jpg",
                                   "_otimizadas/ALINARE/LUMINOUS POCKET 1_30\u0026#x3a;07 3107/POCKET1AGO6786.jpg",
                                   "_otimizadas/ALINARE/LUMINOUS POCKET 1_30\u0026#x3a;07 3107/POCKET1AGO6790.jpg",
                                   "_otimizadas/ALINARE/LUMINOUS POCKET 1_30\u0026#x3a;07 3107/POCKET1AGO6862.jpg",
                                   "_otimizadas/ALINARE/LUMINOUS POCKET 1_30\u0026#x3a;07 3107/POCKET1AGO6865.jpg",
                                   "_otimizadas/ALINARE/LUMINOUS POCKET 1_30\u0026#x3a;07 3107/POCKET1AGO6868.jpg",
                                   "_otimizadas/ALINARE/LUMINOUS POCKET 1_30\u0026#x3a;07 3107/POCKET1AGO6878.jpg",
                                   "_otimizadas/ALINARE/LUMINOUS POCKET 1_30\u0026#x3a;07 3107/POCKET1AGO6890.jpg",
                                   "_otimizadas/ALINARE/LUMINOUS POCKET 1_30\u0026#x3a;07 3107/POCKET1AGO6893.jpg",
                                   "_otimizadas/ALINARE/MOSAIC CUT/5L5A3670 ok.jpg",
                                   "_otimizadas/ALINARE/MOSAIC CUT/ESTILIZADAS/est1.jpg",
                                   "_otimizadas/ALINARE/MOSAIC CUT/ESTILIZADAS/est2.jpg",
                                   "_otimizadas/ALINARE/MOSAIC CUT/ESTILIZADAS/est3.jpg",
                                   "_otimizadas/ALINARE/MOSAIC CUT/ESTILIZADAS/est4.jpg",
                                   "_otimizadas/ALINARE/MOSAIC CUT/ESTILIZADAS/est5.jpg",
                                   "_otimizadas/ALINARE/MOSAIC CUT/ESTILIZADAS/est6.jpg",
                                   "_otimizadas/ALINARE/MOSAIC CUT/ESTILIZADAS/est7.jpg",
                                   "_otimizadas/ALINARE/MOSAIC CUT/NANO_3287.jpg",
                                   "_otimizadas/ALINARE/MOSAIC CUT/NANO_3289.jpg",
                                   "_otimizadas/ALINARE/MOSAIC CUT/NANO_3291.jpg",
                                   "_otimizadas/ALINARE/MOSAIC CUT/NANO_3292.jpg",
                                   "_otimizadas/ALINARE/MOSAIC CUT/NANO_3293.jpg",
                                   "_otimizadas/ALINARE/MOSAIC CUT/NANO_3298.jpg",
                                   "_otimizadas/ALINARE/MOSAIC CUT/NANO_3300.jpg",
                                   "_otimizadas/ALINARE/MOSAIC CUT/NANO_3301.jpg",
                                   "_otimizadas/ALINARE/MOSAIC CUT/NANO_3303.jpg",
                                   "_otimizadas/ALINARE/MOSAIC CUT/NANO_3304.jpg",
                                   "_otimizadas/ALINARE/MOSAIC CUT/NANO_3306.jpg",
                                   "_otimizadas/ALINARE/MOSAIC CUT/NANO_3308.jpg",
                                   "_otimizadas/ALINARE/MOSAIC CUT/NANO_3309.jpg",
                                   "_otimizadas/ALINARE/MOSAIC CUT/NANO_3312.jpg",
                                   "_otimizadas/ALINARE/MOSAIC CUT/NANO_3315.jpg",
                                   "_otimizadas/ALINARE/MOSAIC CUT/NANO_3316.jpg",
                                   "_otimizadas/ALINARE/POCKET 2 04.08/ESTILIZADAS Copiar/ANEL.jpg",
                                   "_otimizadas/ALINARE/POCKET 2 04.08/ESTILIZADAS Copiar/ANEL_CRAVEJADO.jpg",
                                   "_otimizadas/ALINARE/POCKET 2 04.08/ESTILIZADAS Copiar/ANEL_DUPLO.jpg",
                                   "_otimizadas/ALINARE/POCKET 2 04.08/ESTILIZADAS Copiar/BRINCO_CRAVEJADO_jpeg.jpg",
                                   "_otimizadas/ALINARE/POCKET 2 04.08/ESTILIZADAS Copiar/BRINCO_CRAVEJADO_jpg.jpg",
                                   "_otimizadas/ALINARE/POCKET 2 04.08/ESTILIZADAS Copiar/BRINCO_RAQUETE.jpg",
                                   "_otimizadas/ALINARE/POCKET 2 04.08/ESTILIZADAS Copiar/PINGENTE_MENINO.jpg",
                                   "_otimizadas/ALINARE/POCKET 2 04.08/POCKET26905.jpg",
                                   "_otimizadas/ALINARE/POCKET 2 04.08/POCKET26910.jpg",
                                   "_otimizadas/ALINARE/POCKET 2 04.08/POCKET26913.jpg",
                                   "_otimizadas/ALINARE/POCKET 2 04.08/POCKET26916.jpg",
                                   "_otimizadas/ALINARE/POCKET 2 04.08/POCKET26917.jpg",
                                   "_otimizadas/ALINARE/POCKET 2 04.08/POCKET26918.jpg",
                                   "_otimizadas/ALINARE/POCKET 2 04.08/POCKET26927.jpg",
                                   "_otimizadas/ALINARE/POCKET 2 04.08/POCKET26929.jpg",
                                   "_otimizadas/ALINARE/POCKET 2 04.08/POCKET26934.jpg",
                                   "_otimizadas/ALINARE/POCKET 2 04.08/POCKET26936.jpg",
                                   "_otimizadas/ALINARE/POCKET 2 04.08/POCKET26958.jpg",
                                   "_otimizadas/ALINARE/POCKET 2 04.08/POCKET26962.jpg",
                                   "_otimizadas/ALINARE/POCKET 2 04.08/POCKET26969.jpg",
                                   "_otimizadas/ALINARE/POCKET 2 04.08/POCKET26970.jpg",
                                   "_otimizadas/ALINARE/POCKET 2 04.08/POCKET26974.jpg",
                                   "_otimizadas/ALINARE/POCKET 2 04.08/POCKET26978.jpg",
                                   "_otimizadas/ALINARE/POCKET 2 04.08/POCKET26979.jpg",
                                   "_otimizadas/ALINARE/POCKET 2 04.08/POCKET26988.jpg",
                                   "_otimizadas/ALINARE/POCKET 2 04.08/POCKET26992.jpg",
                                   "_otimizadas/ALINARE/POCKET 2 04.08/POCKET27024.jpg",
                                   "_otimizadas/ALINARE/POCKET 3/POCKET34583.jpg",
                                   "_otimizadas/ALINARE/POCKET 3/POCKET34591.jpg",
                                   "_otimizadas/ALINARE/POCKET 3/POCKET34607.jpg",
                                   "_otimizadas/ALINARE/POCKET 3/POCKET34608.jpg",
                                   "_otimizadas/ALINARE/POCKET 3/POCKET34617.jpg",
                                   "_otimizadas/ALINARE/POCKET 3/POCKET34626.jpg",
                                   "_otimizadas/ALINARE/POCKET 3/POCKET34630.jpg",
                                   "_otimizadas/ALINARE/POCKET 3/POCKET34637.jpg",
                                   "_otimizadas/ALINARE/POCKET 3/POCKET34651.jpg",
                                   "_otimizadas/ALINARE/POCKET 3/POCKET34670.jpg",
                                   "_otimizadas/ALINARE/POCKET 3/POCKET34680.jpg",
                                   "_otimizadas/ALINARE/POCKET 3/POCKET34692.jpg"
                               ],
                   "GRACE":  [
                                 "_otimizadas/GRACE/BIJOIAS/GRACEBIJOIAS3824.jpg",
                                 "_otimizadas/GRACE/BIJOIAS/GRACEBIJOIAS3841.jpg",
                                 "_otimizadas/GRACE/BIJOIAS/GRACEBIJOIAS3846.jpg",
                                 "_otimizadas/GRACE/BIJOIAS/GRACEBIJOIAS3857.jpg",
                                 "_otimizadas/GRACE/BIJOIAS/GRACEBIJOIAS3865.jpg",
                                 "_otimizadas/GRACE/BIJOIAS/GRACEBIJOIAS3867.jpg",
                                 "_otimizadas/GRACE/BIJOIAS/GRACEBIJOIAS3891.jpg",
                                 "_otimizadas/GRACE/BIJOIAS/GRACEBIJOIAS3896.jpg",
                                 "_otimizadas/GRACE/BIJOIAS/GRACEBIJOIAS3903.jpg",
                                 "_otimizadas/GRACE/BIJOIAS/GRACEBIJOIAS3912.jpg",
                                 "_otimizadas/GRACE/BIJOIAS/GRACEBIJOIAS3917.jpg",
                                 "_otimizadas/GRACE/BIJOIAS/GRACEBIJOIAS3921.jpg",
                                 "_otimizadas/GRACE/BIJOIAS/GRACEBIJOIAS3937.jpg",
                                 "_otimizadas/GRACE/BIJOIAS/GRACEBIJOIAS3948.jpg",
                                 "_otimizadas/GRACE/BIJOIAS/GRACEBIJOIAS3964.jpg",
                                 "_otimizadas/GRACE/BIJOIAS/GRACEBIJOIAS3979.jpg",
                                 "_otimizadas/GRACE/BIJOIAS/GRACEBIJOIAS3980.jpg",
                                 "_otimizadas/GRACE/BIJOIAS/GRACEBIJOIAS3994 copiar.jpg",
                                 "_otimizadas/GRACE/BIJOIAS/GRACEBIJOIAS3994 copiar2.jpg",
                                 "_otimizadas/GRACE/BIJOIAS/GRACEBIJOIAS4002.jpg",
                                 "_otimizadas/GRACE/BIJOIAS/GRACEBIJOIAS4021.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3362.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3371.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3379.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3408.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3416.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3425.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3436.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3445.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3462.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3463.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3489.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3509.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3514.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3521.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3546.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3568.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3579.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3586.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3599.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3608.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3626.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3642.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3650.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3671.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3701.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3715.2.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3715.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3724.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3726.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3755.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3756.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3774.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3784.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3798.jpg",
                                 "_otimizadas/GRACE/HECTOR/GRACEHECT3803.jpg"
                             ],
                   "NOVITAH":  [
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/ANEIS.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/ANEIS_02.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/ANEL_01.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/COLAR_RAQUETE_jpg.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/COLAR_RAQUETE_png.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4216.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4220.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4232.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4241.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4259.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4282.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4286.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4287.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4294.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4299.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4317.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4337.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4353.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4363.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4376.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4381.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4393.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4398.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4400.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4406.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4437.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4444.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4448.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4451.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4472.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4474.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4475.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4481.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4491.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4504.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4514.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4528.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4534.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4536.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4546.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/Não editadas/NOVITAH_4549.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/NOVITAH_4215.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/NOVITAH_4238.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/NOVITAH_4245.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/NOVITAH_4248.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/NOVITAH_4254.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/NOVITAH_4266.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/NOVITAH_4275.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/NOVITAH_4280.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/NOVITAH_4305.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/NOVITAH_4333.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/NOVITAH_4334.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/NOVITAH_4360.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/NOVITAH_4371.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/NOVITAH_4372.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/NOVITAH_4378.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/NOVITAH_4390.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/NOVITAH_4399.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/NOVITAH_4402.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/NOVITAH_4408.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/NOVITAH_4410.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/NOVITAH_4430.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/NOVITAH_4432.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/NOVITAH_4442.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/NOVITAH_4479.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/NOVITAH_4484.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/NOVITAH_4486.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/NOVITAH_4498.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/NOVITAH_4501.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/NOVITAH_4516.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/NOVITAH_4520.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/NOVITAH_4531.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/NOVITAH_4537.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/PULSEIRA.jpg",
                                   "_otimizadas/NOVITAH/04.08/ESSENCIAL/PULSEIRAS_01.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/NOVITAH_4048.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/NOVITAH_4056.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/NOVITAH_4060.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/NOVITAH_4092.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/NOVITAH_4107.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/NOVITAH_4118.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/NOVITAH_4131.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/NOVITAH_4146.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/NOVITAH_4175.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/NOVITAH_4183.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/NOVITAH_4193.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/SELECT/NOVITAH_4038.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/SELECT/NOVITAH_4045.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/SELECT/NOVITAH_4054.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/SELECT/NOVITAH_4058.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/SELECT/NOVITAH_4064.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/SELECT/NOVITAH_4068.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/SELECT/NOVITAH_4079.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/SELECT/NOVITAH_4080.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/SELECT/NOVITAH_4085.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/SELECT/NOVITAH_4086.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/SELECT/NOVITAH_4089.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/SELECT/NOVITAH_4097.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/SELECT/NOVITAH_4106.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/SELECT/NOVITAH_4110.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/SELECT/NOVITAH_4113.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/SELECT/NOVITAH_4120.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/SELECT/NOVITAH_4125.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/SELECT/NOVITAH_4136.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/SELECT/NOVITAH_4141.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/SELECT/NOVITAH_4154.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/SELECT/NOVITAH_4158.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/SELECT/NOVITAH_4162.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/SELECT/NOVITAH_4173.jpg",
                                   "_otimizadas/NOVITAH/04.08/PARTE 2/SELECT/NOVITAH_4180.jpg",
                                   "_otimizadas/NOVITAH/31.07/5L5A3692-Editar.jpg",
                                   "_otimizadas/NOVITAH/31.07/5L5A3724-Editar.jpg",
                                   "_otimizadas/NOVITAH/31.07/5L5A3732-Editar.jpg",
                                   "_otimizadas/NOVITAH/31.07/5L5A3750-Editar.jpg",
                                   "_otimizadas/NOVITAH/31.07/5L5A3780-Editar.jpg",
                                   "_otimizadas/NOVITAH/31.07/5L5A3808-Editar 2.jpg",
                                   "_otimizadas/NOVITAH/31.07/5L5A3808-Editar.jpg",
                                   "_otimizadas/NOVITAH/31.07/5L5A3867-Editar.jpg",
                                   "_otimizadas/NOVITAH/31.07/5L5A3900-Editar.jpg",
                                   "_otimizadas/NOVITAH/31.07/5L5A3918-Editar.jpg",
                                   "_otimizadas/NOVITAH/31.07/5L5A3922-Editar.jpg",
                                   "_otimizadas/NOVITAH/31.07/5L5A3929-Editar.jpg",
                                   "_otimizadas/NOVITAH/31.07/5L5A3997-Editar.jpg",
                                   "_otimizadas/NOVITAH/31.07/5L5A4011-Editar.jpg",
                                   "_otimizadas/NOVITAH/31.07/5L5A4011-Editar-Editar copiar.jpg",
                                   "_otimizadas/NOVITAH/31.07/5L5A4058-Editar.jpg",
                                   "_otimizadas/NOVITAH/31.07/5L5A4070-Editar.jpg",
                                   "_otimizadas/NOVITAH/31.07/5L5A4151-Editar.jpg",
                                   "_otimizadas/NOVITAH/31.07/5L5A4199.jpg",
                                   "_otimizadas/NOVITAH/31.07/5L5A4199-Editar.jpg"
                               ]
               }
};